export const data = [
  { content: "자동차 점프 스타터" },
  { content: "강아지 자동급식기" },
  { content: "고양이 자동급식기" },
  { content: "자동차 장난감" },
  { content: "자동차용품" },
  { content: "자동차 용품" },
  { content: "자동 연필깎이" },
  { content: "자동차 컴파운드 흠집 제거제" },
  { content: "두잇 자동급식기" },
  { content: "자동차 보조배터리" },
  { content: "자동차 타이어 공기주입기" },
  { content: "자동자동자동차" },
  { content: "자동차 악세사리" },
  { content: "자동차 광택제" },
  { content: "자동차 방향제" },
  { content: "자동 텐트" },
  { content: "자동 사료" },
  { content: "자동 청소기" },
  { content: "자동 휴지통" },
  { content: "자동 분무기" },
];

export const suggestions = [
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
  { content: "추천 검색어", isSuggestion: true },
];
